### ISSUE TITLE
Can you do this over the weekend?

### ISSUE THREAD

**Issue by oren** [knowbody/react-native-online-meetups#12]
For those of us in the west coast, 6 pm GMT means 11 am (the same day).  Is it possible to do that on the weekend? Also, will it be recorded?

**Comment by knowbody** [comment]
great suggestion, asked the current speakers if I that's something we can do for the first meetup...
And yes the meetup is going to be recorded.

**Comment by knowbody** [comment]
I actually spend a bit of time thinking about the timing as obviously I'd like to have as many happy people as possible. But as usual it's hard to make everyone happy.
Maybe 11pm UK time would be better?

This seems like a good tool to visualise everything: http://everytimezone.com/#2016-10-24,600,cn3

![image](https://cloud.githubusercontent.com/assets/3802023/19638653/c8d56e90-99cc-11e6-938c-9f81f1ef1038.png)

**Comment by kelset** [comment]
As someone who lives in EU, probably 11pm UK time is not exactly the best ever, but since probably the majority of the people involved/interested are not EU-based (or are they?) I think it will be fine.
It kinda depends on the duration of each talk. If it is like 1hr each starting 11pm UK, I'll have to rely on the vids ;)

(btw, if you would like some help with editing/mounting the videos pm me on twitter)

**Comment by dhruvdutt** [comment]
In India, this is 1.30 am at night. 
It's the best time for nocturnal peeps. 😀

**Comment by knowbody** [comment]
I'm sorry about that. I'll try to do something about it for the next one. Great to hear you're joining us today

**Comment by heloa-net** [comment]
Hey, just found this out. Sounds really cool! I want to join the next one.
I'm on GMT -2, two hours behind London.

**Comment by nikolenkoanton92** [comment]
@she-dev Hey, I think you need fill here https://github.com/knowbody/react-native-online-meetups/blob/master/interestedSpeakers.md and create PR.

**Comment by heloa-net** [comment]
Thanks @nikolenkoanton92 
For the moment I'll be a non-speaker :)

**Comment by knowbody** [comment]
sorry, I've been ver busy over the last month, I'll try to put everything together and organise one in January.

**Comment by franzejr** [comment]
Hey everyone, I've been talking with @knowbody about the next one and I have created this: https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-1 (this date and time can changed).

Probably we can use the [Remote Meetup](https://www.remotemeetup.com) channel on Bigmarker. This is also one idea I have, create a `React Native Remote Meetup`.

**Comment by knowbody** [comment]
closing this one, let's follow up in the next meetup discussion #34
