### ISSUE TITLE
working with sql [topic suggestion]

### ISSUE THREAD

**Issue by caspg** [knowbody/react-native-online-meetups#13]
I think this could be really interesting if someone could share some knowledge about accessing database on React Native. Both for android and ios.

**Comment by knowbody** [comment]
It's another issue with a topic proposition so I created a separate file where we can keep track of them, and added yours, please see: https://github.com/knowbody/react-native-online-meetups/commit/f6275fba7387293761158b63a53a2e6564fe174f

**Comment by caspg** [comment]
Cool, thanks.
