### ISSUE TITLE
Which platform are we going to use for the meetup?

### ISSUE THREAD

**Issue by sanketsahu** [knowbody/react-native-online-meetups#17]
Which streaming service are we going to use? And are we up for today's meetup?

**Comment by knowbody** [comment]
hey! going to use youtube with the live stream. The meetup is going to take place on Thursday 8pm UK time, can you still make it? That's when I got the best availability from most of the speakers.

**Comment by sanketsahu** [comment]
@knowbody Thanks! Thursday sounds good. I will double check and update my availability.

**Comment by knowbody** [comment]
amazing! thank you!
