### ISSUE TITLE
Next Remote Meetup

### ISSUE THREAD

**Issue by franzejr** [knowbody/react-native-online-meetups#27]
The next React Native Remote Meetup will be on this link: 
https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-1/

**Date/Time:** 15 Feb 17h30 (GMT - London Time). 

Speakers:
- @GantMan 
- @dabit3 
- @sanketsahusoft

For this meetup we already have three speakers. If you're interested in speaking in future meetups, you can left your name here and we will contact you!

Waitlist for the next:
- @axemclion

LINK: https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-1

**Comment by kelset** [comment]
Can't wait!

Will it be recorded and uploaded to YT as last time?

**Comment by franzejr** [comment]
Yes, @kelset!

**Comment by franzejr** [comment]
I'm assuming @GantMan will be the only speaker?

**Comment by kelset** [comment]
Uhm no one else from the https://github.com/knowbody/react-native-online-meetups/blob/master/interestedSpeakers.md is going to participate?

**Comment by GantMan** [comment]
@dabit3 - I summon thee!

**Comment by kelset** [comment]
Probably we should ping directly or via @knowbody the interested speakers, maybe they don't have this repo on Watch.
Imho we should maybe post-pone it until there are ~4 speakers + 1 host.

Moreover, I feel like we should let the other RN communities that this meetup format is back, ex. the FB & Discord groups.
Or am I overengineering it?

**Comment by franzejr** [comment]
You are right @kelset about ping the interested speakers and about postpone the meetup! I totally agree!

My only concern is about the numbers of speakers. Probably 4 is too much if they are giving long talks ? At remoteMeetup we have mostly 2 ~ 3 speakers in each meetup + question it takes more than one hour. :) But probably this is not a concern for the moment, because we just have one speaker atm.

**Comment by kelset** [comment]
Of course it depends on the format of the meetup, in issue #19 in Nov I wrote down some ideas regarding this subject (copypasting it here so it's easier)

> Maybe, instead of Sli.do, a Twitter hashtag may be a good idea: it would still be "redundant" over the chat, but at least (since most of us use it already) it would give the possibility to tag the speaker whose the question is for. That said #reactnativeonlinemeetup is not usable, I mean. Really too long.
> I'm probably not the only one who'd like this "format" to be frequent over time, let's say every 2/3 weeks. The issue in this case would be that, keeping the format of having different people presenting something each time, maybe in 3/4 appointments there would be no more speakers. So I have this hypothesis to present you: 4/5 people each time, 2 of which have to "present" something (like the guys did this time) and then the "host" will present an argument, or question, or something (which may be decided starting from the list of Suggested Topics) and have the speakers talk around that for some time. The ideal situation would be, in that case, that the "topic" is decided like at least one week before so that people can start write questions around it that the speakers will try to answer (a way to do this could be to have a dedicated Issue here on GitHub for every meetup). Going for some version of this format would allow to have people which can propose to be on the "panel" without having to present something (but they feel confident about the topic so they want to be there to talk about it) and having people who can be on the panel more than one time.

We should maybe try the Feb one with the format you propose (2~3 speakers with "long" 20-mins presentations) and see the response of everyone watching it.

**Comment by GantMan** [comment]
@franzejr - I see you're making waves in RN, are you coming to Chain React Conf?

**Comment by dabit3** [comment]
Hey thanks for pinging me @GantMan, and thanks to those who are setting this up! I can't make it on Feb 8 but if this gets postponed I can hopefully fit it in my schedule :)

**Comment by dabit3** [comment]
Also, I'll be sure to attempt to get the word out once the date has been confirmed, I'll be checking this thread out throughout the day.

**Comment by franzejr** [comment]
@GantMan, probably not! I will check the schedule and everything. Thanks for the reminder!

**Comment by franzejr** [comment]
I postponed a bit the date. Now @dabit3 will also give us a talk!! 

https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-1

**Comment by dabit3** [comment]
thanks @franzejr looking forward to joining you all!

**Comment by knowbody** [comment]
Thank you @franzejr for looking after it! 💙

**Comment by franzejr** [comment]
Closing this issue and going to talk about the next meetup on: https://github.com/knowbody/react-native-online-meetups/issues/34
