### ISSUE TITLE
Speakers for Wednesday, Feb 15 

### ISSUE THREAD

**Issue by dabit3** [knowbody/react-native-online-meetups#29]
If you are interested in speaking at the next meetup, please let us know here so we can get you added!

**Comment by UADACID** [comment]
interesting 💃

**Comment by sanketsahu** [comment]
I would love to present at this online meet up!

I am Kumar Sanket, co-author of NativeBase.
We are building a framework for React and React Native at the moment named ReazyFramework.io and rolling out NativeBase 2.0

I would like to talk about it in the meet up.

**Comment by franzejr** [comment]
Nice @sanketsahusoft ! Can you DM me on Twitter and we can have you added ?

**Comment by axemclion** [comment]
I would like to talk about Visual Studio Mobile Center - http://azure.mobile.com

**Comment by franzejr** [comment]
@sanketsahusoft, you should receive an invitation.

@axemclion, for this next meetup Feb 15 we already have three speakers. Can we schedule your talk for the next next meetup ?

**Comment by franzejr** [comment]
Speakers for Wednesday, Feb 15:

- @GantMan 
- @dabit3 
- @sanketsahusoft

More information: https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-1

WaitList for the next:
- @axemclion
