### ISSUE TITLE
Exponent 

### ISSUE THREAD

**Issue by oren** [knowbody/react-native-online-meetups#9]
I am new to react native and would like to hear other devs with experience with exponent. Just a suggestion for a topic.

Thanks!

**Comment by knowbody** [comment]
I might speak about it. That's what I've been doing for past month or so

**Comment by oren** [comment]
Awesome!

**Comment by knowbody** [comment]
It's another issue with a topic proposition so I created a separate file where we can keep track of them, and added yours, please see: https://github.com/knowbody/react-native-online-meetups/commit/f6275fba7387293761158b63a53a2e6564fe174f
